version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cvfast-postgres
    restart: always
    environment:
      POSTGRES_DB: cvfast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cvfast-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Api
      dockerfile: CVFastApi/Dockerfile
    container_name: cvfast-backend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cvfast-network

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: cvfast-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cvfast-network

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: cvfast-nginx
    restart: always
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - cvfast-network

volumes:
  postgres_data:
  frontend-dist:

networks:
  cvfast-network:
    driver: bridge
