version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cvfast-postgres-dev
    restart: always
    environment:
      POSTGRES_DB: cvfast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - cvfast-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  cvfast-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
